spring.application.name=AttendanceDB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:31001/AttendanceDb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=9030
logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
